import './globals.css'
import {Inter} from 'next/font/google'
import HeaderComponent from "@/app/components/HeaderComponent";
import FooterComponent from "@/app/components/FooterComponent";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className="p-10">
            <HeaderComponent/>
            <main className="mt-10">{children}</main>
            <div className="mt-[1000px]"><FooterComponent/></div>
        </div>
        </body>
        </html>
    )
}
